name: DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ejecutar pruebas unitarias
        run: pytest tests/

      - name: Construir Docker image
        run: docker build -t gestion-clientes .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue en AWS (simulado)
        run: echo "Aquí implementarías tu despliegue real en AWS con AWS CLI."


